Fix for issue #17
brentp/cyvcf2 pull request #262
Opened 2023-05-04 07:53 UTC by davmlaw

Fix for issue https://github.com/brentp/cyvcf2/issues/17

This adds a check for bcf_get_genotypes returning -1, returning same exception as other methods when calling GT methods w/o GT present, avoiding segmentation fault

2023-05-04 14:10 UTC, brentp requested changes
Thanks very much for this. I wrote a couple of comments.

2023-05-04 14:10 UTC, brentp commented on cyvcf2/tests/test_reader.py
> +    for v in vcf:
can you use: `with pytest.raises(Exception):` as a more direct way to test this?

2023-05-04 14:10 UTC, brentp commented on cyvcf2/cyvcf2.pyx
> +                    raise Exception("error parsing genotypes")
can you add a hint here that they may simply be absent, e.g.: `"error parsing genotypes; they may be absent from this record"` .

2023-05-05 00:38 UTC, davmlaw commented
I've implemented your suggestions and pushed to my fork

2023-05-05 14:21 UTC, merged

2023-05-05 14:22 UTC, brentp commented
thank you! I'll tag a new release shortly.